import { useState, useRef, useEffect } from 'react'
import type { DesignResponse } from '@/lib/api'
import { toast } from './Toast'
import GeneCircuit from './GeneCircuit'
import InteractivePlasmidMap from './InteractivePlasmidMap'
import ShareButton from './ShareButton'
import { track } from '@/hooks/useAnalytics'

interface Props {
  design: DesignResponse
}

function downloadFile(content: string, filename: string, type = 'text/plain') {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function downloadDataUrl(dataUrl: string, filename: string) {
  if (!dataUrl.startsWith('data:')) return
  const a = document.createElement('a')
  a.href = dataUrl
  a.download = filename
  a.click()
}

function ExportBtn({ onClick, label }: { onClick: () => void; label: string }) {
  return (
    <button
      onClick={onClick}
      className="px-2 py-1 text-[10px] font-medium text-gray-400 bg-gray-800 hover:bg-gray-700 hover:text-gray-200 rounded border border-gray-700 transition-colors"
    >
      {label}
    </button>
  )
}

export default function ResultsPanel({ design }: Props) {
  const panelRef = useRef<HTMLDivElement>(null)
  const slug = design.design_name.replace(/\s+/g, '_')

  // Auto-scroll to results when a new design appears
  const lastSeenId = useRef<string | null>(null)
  useEffect(() => {
    if (design.id && design.id !== lastSeenId.current) {
      panelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
      // Only toast for genuinely new designs (not history navigation)
      if (lastSeenId.current !== null) {
        toast('Design complete. All files ready to download.', 'success')
      }
      lastSeenId.current = design.id
    }
  }, [design.id])

  function downloadFasta() {
    track('feature_use', { page: 'studio', element: 'export_fasta' })
    downloadFile(design.fasta_content, `${slug}.fasta`)
    toast('FASTA file downloaded')
  }

  function downloadGenBank() {
    if (!design.genbank_content) return
    downloadFile(design.genbank_content, `${slug}.gb`)
    toast('GenBank file downloaded')
  }

  function downloadPlasmidSvg() {
    const mapData = design.plasmid_map_data
    if (!mapData?.png_base64) return
    try {
      const decoded = atob(mapData.png_base64)
      if (decoded.startsWith('<svg')) {
        downloadFile(decoded, `${slug}_plasmid.svg`, 'image/svg+xml')
      } else {
        downloadDataUrl(`data:image/png;base64,${mapData.png_base64}`, `${slug}_plasmid.png`)
      }
    } catch {
      downloadDataUrl(`data:image/png;base64,${mapData.png_base64}`, `${slug}_plasmid.png`)
    }
  }

  function downloadPrimersCSV() {
    const primers = design.assembly_plan?.primers
    if (!primers?.length) return
    const rows = ['Gene,Direction,Sequence,Length,Tm (°C),GC%']
    for (const p of primers) {
      if (p.forward) rows.push(`${p.gene},Forward,${p.forward.sequence},${p.forward.length},${p.forward.tm},${(p.forward.gc * 100).toFixed(1)}`)
      if (p.reverse) rows.push(`${p.gene},Reverse,${p.reverse.sequence},${p.reverse.length},${p.reverse.tm},${(p.reverse.gc * 100).toFixed(1)}`)
    }
    downloadFile(rows.join('\n'), `${slug}_primers.csv`); toast('Primers CSV downloaded')
  }

  function downloadAssemblyPlan() {
    const a = design.assembly_plan
    if (!a) return
    const lines = [
      `# Assembly Plan: ${design.design_name}`,
      `Generated by Progenx\n`,
      `## Origin of Replication`,
      `${a.origin_of_replication?.name} (${a.origin_of_replication?.copy_number})`,
      `${a.origin_of_replication?.rationale}\n`,
      `## Selection Marker`,
      `${a.selection_marker?.name}`,
      `${a.selection_marker?.rationale}\n`,
      `## Assembly Method`,
      `${a.assembly_method?.name}`,
      `${a.assembly_method?.description}`,
      ...(a.assembly_method?.steps?.map((s: string, i: number) => `${i + 1}. ${s}`) || []),
      `\n## Biocontainment`,
      `${a.kill_switch?.name}`,
      `${a.kill_switch?.mechanism}\n`,
      `## RBS Strategy`,
      `${a.rbs_notes?.strategy}`,
      `${a.rbs_notes?.tool_note}\n`,
      `Estimated construct size: ${a.estimated_total_size_bp?.toLocaleString()} bp`,
    ]
    if (a.primers?.length) {
      lines.push(`\n## Primers`)
      for (const p of a.primers) {
        lines.push(`\n### ${p.gene}`)
        if (p.forward) lines.push(`Forward: ${p.forward.sequence} (Tm ${p.forward.tm}°C, ${p.forward.length}bp)`)
        if (p.reverse) lines.push(`Reverse: ${p.reverse.sequence} (Tm ${p.reverse.tm}°C, ${p.reverse.length}bp)`)
      }
    }
    downloadFile(lines.join('\n'), `${slug}_assembly.md`); toast('Assembly plan downloaded')
  }

  function downloadFullReport() {
    track('feature_use', { page: 'studio', element: 'export_full_report' })
    const fba = design.fba_results || {} as any
    const lines = [
      `# ${design.design_name}`,
      `Host: ${design.host_organism}`,
      `Model: ${design.model_used}`,
      `Generated by Progenx\n`,
      `## Organism Summary`,
      design.organism_summary,
      `\n## Safety Score: ${Math.round(design.safety_score * 100)}%`,
      design.dual_use_assessment,
      ...(design.safety_flags?.map(f => `- ${f}`) || []),
      `\n## Gene Circuit`,
      ...(design.gene_circuit?.genes?.map((g: any) => `- **${g.name}**: ${g.function} (${g.source_organism})`) || []),
      `\nPromoters: ${design.gene_circuit?.promoters?.join(', ')}`,
      `Terminators: ${design.gene_circuit?.terminators?.join(', ')}`,
      `\n## Gene Sequences (NCBI)`,
      ...Object.entries(design.gene_sequences || {}).map(([name, d]: [string, any]) =>
        `- **${name}** [${d.accession}] ${d.length} ${d.type === 'protein' ? 'aa' : 'bp'} - ${d.source} (${d.confidence || '?'} confidence)`
      ),
      `\n## Codon-Optimized Sequences`,
      ...Object.entries(design.codon_optimized || {}).map(([name, d]: [string, any]) =>
        `- **${name}**: ${d.length_bp} bp, CAI ${d.cai_score}, GC ${((d.gc_content || 0) * 100).toFixed(1)}%`
      ),
      `\n## Flux Balance Analysis`,
      fba.summary || 'N/A',
      `\n## Assembly Plan`,
      design.assembly_plan?.summary || 'N/A',
      `\n## Metrics`,
      `Simulated Yield: ${design.simulated_yield}`,
      `Synthesis Cost: ${design.estimated_cost}`,
      `Construct Size: ${design.dna_sequence?.length?.toLocaleString()} bp`,
      `Target Product: ${design.target_product || 'N/A'}`,
      `\n---`,
      `${design.disclaimer}`,
    ]
    downloadFile(lines.join('\n'), `${slug}_full_report.md`); toast('Full report downloaded')
  }

  function downloadDesignJSON() {
    track('feature_use', { page: 'studio', element: 'export_json' })
    downloadFile(JSON.stringify(design, null, 2), `${slug}_data.json`, 'application/json'); toast('JSON data downloaded')
  }

  function safetyColor(score: number) {
    if (score >= 0.8) return 'text-green-400 bg-green-500/10 border-green-500/30'
    if (score >= 0.5) return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30'
    return 'text-red-400 bg-red-500/10 border-red-500/30'
  }

  const [activeTab, setActiveTab] = useState<'overview' | 'map' | 'files' | 'safety' | 'assembly'>('overview')

  const fba = design.fba_results || {} as any
  const assembly = design.assembly_plan || {} as any
  const geneSeqs = design.gene_sequences || {}
  const codonOpt = design.codon_optimized || {}
  const plasmid = design.plasmid_map_data || {} as any

  const tabs = [
    { id: 'overview' as const, label: 'Overview', icon: (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>
      </svg>
    )},
    { id: 'map' as const, label: 'Map', icon: (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 000 20 14.5 14.5 0 000-20"/>
      </svg>
    )},
    { id: 'files' as const, label: 'Files', icon: (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/>
      </svg>
    )},
    { id: 'safety' as const, label: 'Safety', icon: (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
      </svg>
    )},
    { id: 'assembly' as const, label: 'Build', icon: (
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14.7 6.3a1 1 0 000 1.4l1.6 1.6a1 1 0 001.4 0l3.77-3.77a6 6 0 01-7.94 7.94l-6.91 6.91a2.12 2.12 0 01-3-3l6.91-6.91a6 6 0 017.94-7.94l-3.76 3.76z"/>
      </svg>
    )},
  ]

  return (
    <div ref={panelRef} className="space-y-4">
      {/* Disclaimer */}
      <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg px-4 py-2 text-[11px] text-amber-300/80">
        For learning and testing ideas only. Not lab-ready without expert review.
      </div>

      {/* Conceptual Design Banner */}
      {design.conceptual_banner && (
        <div className="bg-red-500/10 border border-red-500/30 rounded-lg px-4 py-3 text-sm text-red-300 font-semibold">
          {design.conceptual_banner}
        </div>
      )}

      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="text-xl font-semibold text-white">{design.design_name}</h2>
          <p className="text-sm text-gray-500 mt-1">
            {design.host_organism} | Built in {design.generation_time_sec}s
          </p>
        </div>
        <ShareButton designId={design.id} designName={design.design_name} isPublic={design.is_public} />
      </div>

      {/* Tab navigation — segmented control */}
      <div className="flex items-center gap-0.5 p-1 bg-gray-900/80 border border-gray-800/80 rounded-xl overflow-x-auto">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => { setActiveTab(tab.id); track('feature_use', { page: 'studio', element: `tab_${tab.id}` }); panelRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }}
            className={`tab-segment flex items-center gap-1.5 px-2.5 sm:px-3.5 py-2 text-xs sm:text-sm font-medium rounded-lg transition-all whitespace-nowrap ${
              activeTab === tab.id
                ? 'tab-segment-active bg-gray-800 text-white'
                : 'text-gray-500 hover:text-gray-300 hover:bg-gray-800/40'
            }`}
          >
            <span className={activeTab === tab.id ? 'text-cyan-400' : 'text-gray-600'}>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
        {/* Export action */}
        <div className="ml-auto flex items-center gap-1 pl-2 border-l border-gray-800/60">
          <button
            onClick={downloadFullReport}
            className="flex items-center gap-1.5 px-3 py-1.5 text-[11px] font-medium text-gray-400 bg-gray-800/40 hover:bg-gray-800 hover:text-gray-200 rounded-lg border border-gray-700/50 transition-colors"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            Export All
          </button>
        </div>
      </div>

      {/* ─── OVERVIEW TAB ─── */}
      {activeTab === 'overview' && (
      <>
      {/* Summary */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
        <h3 className="text-sm font-medium mb-2 text-white">What this organism does</h3>
        <p className="text-sm text-gray-400 whitespace-pre-wrap leading-relaxed">{design.organism_summary}</p>
      </div>

      {/* Safety Score with gauge */}
      <div className={`rounded-xl p-4 border ${safetyColor(design.safety_score)}`}>
        <div className="flex items-start gap-4">
          <SafetyGauge score={design.safety_score} />
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-medium mb-1">Safety Score</h3>
            <p className="text-sm opacity-80 mb-2">{design.dual_use_assessment}</p>
            {design.safety_flags.length > 0 && (
              <ul className="text-xs space-y-1 mt-2">
                {design.safety_flags.map((flag, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mt-0.5 shrink-0 opacity-70"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                    <span>{flag}</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>

      {/* Gene Circuit (visual) */}
      <GeneCircuit circuitJson={JSON.stringify(design.gene_circuit)} />

      {/* Gene Parts Table */}
      {Object.keys(geneSeqs).length > 0 && (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl overflow-hidden">
          <div className="p-4 border-b border-gray-800">
            <h3 className="text-sm font-semibold text-white">Parts Used in This Design</h3>
            <p className="text-xs text-gray-500 mt-0.5">Each part is a real protein from NCBI. Click an accession to view it on NCBI.</p>
          </div>
          <div className="divide-y divide-gray-800/60">
            {Object.entries(geneSeqs).map(([name, data]: [string, any], idx) => {
              const opt = codonOpt[name]
              return (
                <div key={name} className={`p-4 hover:bg-gray-800/30 transition-colors ${idx % 2 === 1 ? 'bg-gray-800/10' : ''}`}>
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-sm font-bold text-white">{name}</span>
                        <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${
                          data.source === 'ncbi_registry' ? 'bg-green-500/20 text-green-400' :
                          data.source === 'ncbi_search' ? 'bg-blue-500/20 text-blue-400' :
                          data.conceptual_only ? 'bg-orange-500/20 text-orange-400' :
                          'bg-gray-800 text-gray-400'
                        }`}>
                          {data.source === 'ncbi_registry' ? 'Verified' :
                           data.source === 'ncbi_search' ? 'Search' :
                           data.conceptual_only ? 'Conceptual' : '?'}
                        </span>
                        {data.confidence && data.confidence !== 'unknown' && (
                          <span className={`text-[10px] px-1.5 py-0.5 rounded ${
                            data.confidence === 'high' ? 'bg-green-500/10 text-green-400' :
                            data.confidence === 'medium' ? 'bg-cyan-500/10 text-cyan-400' :
                            'bg-yellow-500/10 text-yellow-400'
                          }`}>{data.confidence}</span>
                        )}
                      </div>
                      <p className="text-xs text-gray-400">{data.description || data.function || ''}</p>
                      {data.accession && (
                        <a
                          href={`https://www.ncbi.nlm.nih.gov/protein/${data.accession}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[11px] text-cyan-500 hover:text-cyan-400 mt-1 inline-block"
                        >
                          {data.accession} on NCBI &rarr;
                        </a>
                      )}
                    </div>
                    <div className="text-right shrink-0 space-y-1">
                      {data.length > 0 && (
                        <p className="text-xs text-gray-400">{data.length} {data.type === 'protein' ? 'aa' : 'bp'}</p>
                      )}
                      {opt && (
                        <div className="text-[10px] text-gray-500 space-y-0.5">
                          <p>{opt.length_bp?.toLocaleString()} bp optimized</p>
                          <p>GC {((opt.gc_content || 0) * 100).toFixed(1)}% | CAI {opt.cai_score ?? '?'}</p>
                        </div>
                      )}
                    </div>
                  </div>
                  {data.warning && (
                    <p className="text-xs text-red-400 mt-2 flex items-start gap-1">
                      <span className="shrink-0">&#9888;</span>{data.warning}
                    </p>
                  )}
                  {data.variant_predictions?.beneficial_mutations?.length > 0 && (
                    <div className="mt-2 pt-2 border-t border-gray-800">
                      <p className="text-[10px] text-emerald-400 font-medium mb-1">
                        ESM-2 predicted {data.variant_predictions.total_beneficial} possible improvements:
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {data.variant_predictions.beneficial_mutations.slice(0, 6).map((m: any) => (
                          <span key={m.notation} className="text-[10px] px-1.5 py-0.5 bg-emerald-500/10 text-emerald-400 rounded font-mono" title={`Score: +${m.score}`}>
                            {m.notation}
                          </span>
                        ))}
                        {data.variant_predictions.beneficial_mutations.length > 6 && (
                          <span className="text-[10px] text-gray-600">+{data.variant_predictions.beneficial_mutations.length - 6} more</span>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )
            })}
          </div>
          <div className="p-3 border-t border-gray-800 bg-gray-800/20">
            <p className="text-[11px] text-gray-500 text-center">
              Optimized for {design.host_organism} | {Object.keys(codonOpt).length} genes codon-optimized
            </p>
          </div>
        </div>
      )}

      {/* Quick stats */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl overflow-hidden">
        <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-gray-800/60 divide-y md:divide-y-0 divide-gray-800/60">
          <div className="p-4 text-center">
            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1.5">Target Product</p>
            <p className="text-sm font-semibold text-white">{design.target_product || 'N/A'}</p>
          </div>
          <div className="p-4 text-center">
            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1.5">Construct Size</p>
            <p className="text-sm font-semibold text-white">{design.dna_sequence.length.toLocaleString()} bp</p>
          </div>
          <div className="p-4 text-center">
            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1.5">Synthesis Cost</p>
            <p className="text-sm font-semibold text-white">
              {design.estimated_cost ? design.estimated_cost.split('(')[0].trim() : 'N/A'}
            </p>
            <p className="text-[9px] text-gray-600 mt-0.5">2026 pricing</p>
          </div>
          <div className="p-4 text-center">
            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1.5">Yield Estimate</p>
            {fba.source === 'no_model' || !fba.estimated_titer_g_per_L ? (
              <>
                <p className="text-sm font-semibold text-gray-500">No model</p>
                <p className="text-[9px] text-gray-600 mt-0.5">Unsupported chassis</p>
              </>
            ) : (
              <>
                <p className="text-sm font-semibold text-white">{fba.estimated_titer_g_per_L} g/L</p>
                <p className="text-[9px] text-gray-600 mt-0.5">theoretical max</p>
              </>
            )}
          </div>
        </div>
        {fba.source === 'no_model' && (
          <div className="px-4 py-2.5 border-t border-gray-800 bg-gray-800/20">
            <p className="text-[11px] text-gray-500 text-center">
              Metabolic modeling requires E. coli or P. putida as the chassis organism.
              {design.host_organism && ` ${design.host_organism} does not have a genome-scale model yet.`}
            </p>
          </div>
        )}
      </div>
      </>
      )}

      {/* ─── MAP TAB ─── */}
      {activeTab === 'map' && plasmid.features?.length > 0 && (
        <InteractivePlasmidMap
          features={plasmid.features}
          totalLength={plasmid.total_length_bp || 5000}
          designName={design.design_name}
          featureData={plasmid.feature_data}
        />
      )}

      {/* ─── FILES TAB ─── */}
      {activeTab === 'files' && (
      <>
      {/* Export options */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
        <h3 className="text-sm font-medium text-white mb-3">Download Your Design Files</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
          <button onClick={downloadFasta} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">FASTA</p>
            <p className="text-[10px] text-gray-500">DNA sequences</p>
          </button>
          {design.genbank_content && (
          <button onClick={downloadGenBank} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">GenBank</p>
            <p className="text-[10px] text-gray-500">Opens in SnapGene</p>
          </button>
          )}
          <button onClick={downloadPlasmidSvg} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">Plasmid SVG</p>
            <p className="text-[10px] text-gray-500">Vector map</p>
          </button>
          {(assembly.primers?.length ?? 0) > 0 && (
          <button onClick={downloadPrimersCSV} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="9" y1="3" x2="9" y2="21"/><line x1="15" y1="3" x2="15" y2="21"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">Primers CSV</p>
            <p className="text-[10px] text-gray-500">Ready to order</p>
          </button>
          )}
          <button onClick={downloadFullReport} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">Full Report</p>
            <p className="text-[10px] text-gray-500">Everything in one doc</p>
          </button>
          <button onClick={downloadDesignJSON} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">JSON</p>
            <p className="text-[10px] text-gray-500">For developers</p>
          </button>
          <button onClick={() => { navigator.clipboard.writeText(design.dna_sequence); toast('DNA sequence copied to clipboard') }} className="group p-3 bg-gray-800/30 border border-gray-700/60 rounded-lg hover:border-cyan-500/30 hover:bg-gray-800/50 transition-all text-center">
            <div className="flex justify-center mb-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-gray-500 group-hover:text-cyan-400 transition-colors">
                <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
              </svg>
            </div>
            <p className="text-sm font-medium text-white">Copy DNA</p>
            <p className="text-[10px] text-gray-500">To clipboard</p>
          </button>
        </div>
      </div>

      {/* DNA sequence preview */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
        <h3 className="text-sm font-medium text-white mb-2">Construct Sequence</h3>
        <pre className="text-xs font-mono bg-gray-800/50 p-3 rounded-lg overflow-x-auto max-h-32 text-gray-400">
          {design.dna_sequence.match(/.{1,80}/g)?.join('\n') || 'No sequence'}
        </pre>
      </div>

      {/* Codon optimization details */}
      {Object.keys(codonOpt).length > 0 && (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
          <h3 className="text-sm font-medium text-white mb-3">Codon-Optimized Sequences</h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2 mb-3">
            {Object.entries(codonOpt).map(([name, data]: [string, any]) => (
              <div key={name} className="bg-gray-800/50 rounded-lg p-2 text-center">
                <p className="text-xs font-medium text-white">{name}</p>
                <p className="text-sm font-bold text-white">{data.length_bp?.toLocaleString()} bp</p>
                {data.cai_score != null && <p className="text-[10px] text-gray-500">CAI: {data.cai_score}</p>}
                <p className="text-[10px] text-gray-500">GC: {((data.gc_content || 0) * 100).toFixed(1)}%</p>
              </div>
            ))}
          </div>
          <p className="text-xs text-gray-500">Optimized for {design.host_organism}</p>
        </div>
      )}

      {/* Vendor links */}
      <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
        <h3 className="text-sm font-medium text-white mb-1">Ready to Order Synthesis?</h3>
        <p className="text-xs text-gray-500 mb-3">
          Sequences go through additional biosecurity screening before synthesis.
        </p>
        <div className="flex gap-2">
          <a href="https://www.twistbioscience.com" target="_blank" rel="noopener noreferrer"
            className="px-4 py-2 border border-gray-700 rounded-lg text-xs font-medium text-gray-300 hover:bg-gray-800 hover:border-gray-600">Twist Bioscience</a>
          <a href="https://www.idtdna.com" target="_blank" rel="noopener noreferrer"
            className="px-4 py-2 border border-gray-700 rounded-lg text-xs font-medium text-gray-300 hover:bg-gray-800 hover:border-gray-600">IDT</a>
        </div>
      </div>
      </>
      )}

      {/* ─── SAFETY TAB ─── */}
      {activeTab === 'safety' && (
      <>
      {/* Safety Score with gauge */}
      <div className={`rounded-xl p-4 border ${safetyColor(design.safety_score)}`}>
        <div className="flex items-start gap-4">
          <SafetyGauge score={design.safety_score} />
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-medium mb-1">Safety Score</h3>
            <p className="text-sm opacity-80 mb-2">{design.dual_use_assessment}</p>
            {design.safety_flags.length > 0 && (
              <ul className="text-xs space-y-1 mt-2">
                {design.safety_flags.map((flag, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="mt-0.5 shrink-0 opacity-70"><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                    <span>{flag}</span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>

      {/* Gene confidence breakdown */}
      {Object.keys(geneSeqs).length > 0 && (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
          <h3 className="text-sm font-medium text-white mb-3">Gene Verification Status</h3>
          <div className="space-y-2">
            {Object.entries(geneSeqs).map(([name, data]: [string, any]) => (
              <div key={name} className="flex items-center justify-between text-sm py-1.5 border-b border-gray-800 last:border-0">
                <span className="font-medium text-white">{name}</span>
                <div className="flex items-center gap-2">
                  <span className={`text-xs px-1.5 py-0.5 rounded ${
                    data.source === 'ncbi_registry' ? 'bg-green-500/20 text-green-400' :
                    data.source === 'ncbi_search' ? 'bg-blue-500/20 text-blue-400' :
                    'bg-gray-800 text-gray-400'
                  }`}>
                    {data.source === 'ncbi_registry' ? 'Verified' : data.source === 'ncbi_search' ? 'Found' : 'Unverified'}
                  </span>
                  {data.confidence && data.confidence !== 'unknown' && (
                    <span className={`text-[10px] px-1 py-0.5 rounded ${
                      data.confidence === 'high' ? 'bg-green-500/15 text-green-400' :
                      data.confidence === 'medium' ? 'bg-blue-500/15 text-blue-400' :
                      'bg-yellow-500/15 text-yellow-400'
                    }`}>{data.confidence}</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
      </>
      )}

      {/* ─── BUILD PLAN TAB ─── */}
      {activeTab === 'assembly' && (
      <>
      {/* FBA Results */}
      {fba.summary && (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
          <h3 className="text-sm font-medium mb-3">
            Flux Balance Analysis
            {fba.source === 'cobra_fba' && <span className="text-xs ml-2 px-1.5 py-0.5 bg-green-500/20 text-green-400 rounded">COBRApy</span>}
            {fba.source === 'heuristic_fallback' && <span className="text-xs ml-2 px-1.5 py-0.5 bg-yellow-500/20 text-yellow-400 rounded">Heuristic</span>}
          </h3>
          {fba.source !== 'no_model' ? (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Metric label="WT Growth" value={fba.wild_type_growth_rate != null ? `${fba.wild_type_growth_rate} h⁻¹` : 'N/A'} />
            <Metric label="With Burden" value={fba.burdened_growth_rate != null ? `${fba.burdened_growth_rate} h⁻¹` : 'N/A'} />
            <Metric label="Growth Hit" value={fba.growth_reduction_pct != null ? `-${fba.growth_reduction_pct}%` : 'N/A'} />
            <Metric label="Max Titer (theoretical)" value={fba.estimated_titer_g_per_L != null ? `${fba.estimated_titer_g_per_L} g/L` : 'N/A'} />
          </div>
          ) : (
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-3 mb-3">
            <p className="text-sm text-amber-300 font-medium">No metabolic model available for this chassis organism.</p>
            <p className="text-xs text-amber-400 mt-1">FBA predictions require a genome-scale model. Supported: E. coli (iJO1366), P. putida (iJN1463).</p>
          </div>
          )}
          {fba.model_used && fba.model_used !== 'heuristic_fallback' && (
            <p className="text-xs text-gray-500">
              Model: {fba.model_used} ({fba.model_genes} genes, {fba.model_reactions} reactions) |
              Burden: {fba.metabolic_burden_estimate} | {fba.heterologous_genes} heterologous genes
            </p>
          )}
          <pre className="text-xs font-mono bg-gray-800/50 p-3 rounded-lg mt-2 whitespace-pre-wrap">{fba.summary}</pre>
        </div>
      )}

      {/* Assembly Plan */}
      {assembly.summary && (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-4">
          <h3 className="text-sm font-medium mb-3">Assembly Plan</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
            {assembly.origin_of_replication && (
              <div className="bg-gray-800/50 rounded-lg p-3">
                <p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Origin</p>
                <p className="text-sm font-medium">{assembly.origin_of_replication.name}</p>
                <p className="text-xs text-gray-500">{assembly.origin_of_replication.copy_number}</p>
                <p className="text-xs text-gray-500 mt-1">{assembly.origin_of_replication.rationale}</p>
              </div>
            )}
            {assembly.selection_marker && (
              <div className="bg-gray-800/50 rounded-lg p-3">
                <p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Selection</p>
                <p className="text-sm font-medium">{assembly.selection_marker.name}</p>
                <p className="text-xs text-gray-500 mt-1">{assembly.selection_marker.rationale}</p>
              </div>
            )}
            {assembly.assembly_method && (
              <div className="bg-gray-800/50 rounded-lg p-3">
                <p className="text-xs font-semibold uppercase tracking-wider text-gray-500">Assembly</p>
                <p className="text-sm font-medium">{assembly.assembly_method.name}</p>
                <p className="text-xs text-gray-500">{assembly.assembly_method.description}</p>
                {assembly.assembly_method.steps && (
                  <ol className="text-xs text-gray-500 mt-1 list-decimal list-inside space-y-0.5">
                    {assembly.assembly_method.steps.map((s: string, i: number) => <li key={i}>{s}</li>)}
                  </ol>
                )}
              </div>
            )}
            {assembly.kill_switch && (
              <div className="bg-red-500/10 rounded-lg p-3 border border-red-500/30">
                <p className="text-xs font-semibold uppercase tracking-wider text-red-400">Biocontainment</p>
                <p className="text-sm font-medium text-red-300">{assembly.kill_switch.name}</p>
                <p className="text-xs text-red-400 mt-1">{assembly.kill_switch.mechanism}</p>
              </div>
            )}
          </div>
          {assembly.rbs_notes && (
            <div className="text-xs text-gray-500 mt-2">
              <strong>RBS:</strong> {assembly.rbs_notes.strategy}
              <br /><em>{assembly.rbs_notes.tool_note}</em>
            </div>
          )}
          {(assembly.primers?.length ?? 0) > 0 && (
            <div className="mt-3 pt-3 border-t border-gray-800">
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs font-semibold uppercase tracking-wider text-gray-400">Suggested Primers</p>
                <ExportBtn onClick={downloadPrimersCSV} label="CSV" />
              </div>
              <div className="space-y-1.5">
                {assembly.primers!.map((p: any) => (
                  <div key={p.gene} className="bg-gray-800/50 rounded-lg p-2">
                    <p className="text-xs font-medium mb-1">{p.gene}</p>
                    <div className="grid grid-cols-2 gap-2">
                      <div>
                        <p className="text-[10px] text-gray-500">Forward (Tm {p.forward?.tm}°C)</p>
                        <p className="text-[10px] font-mono break-all">{p.forward?.sequence}</p>
                      </div>
                      <div>
                        <p className="text-[10px] text-gray-500">Reverse (Tm {p.reverse?.tm}°C)</p>
                        <p className="text-[10px] font-mono break-all">{p.reverse?.sequence}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
              <p className="text-[10px] text-gray-500 mt-1">
                SantaLucia (1998) nearest-neighbor model. 500 nM primer, 50 mM Na+. Verify with NEB Tm Calculator before ordering.
              </p>
            </div>
          )}
        </div>
      )}

      </>
      )}

      {/* Bottom disclaimer on all tabs */}
      <div className="text-[11px] text-gray-600 text-center pt-2">
        For learning and testing ideas only. Not lab-ready without expert review.
      </div>
    </div>
  )
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-gray-900/50 border border-gray-800 rounded-lg p-3">
      <p className="text-[10px] text-gray-500 uppercase tracking-wider">{label}</p>
      <p className="text-sm font-medium mt-1 break-words">{value || 'N/A'}</p>
    </div>
  )
}

function SafetyGauge({ score }: { score: number }) {
  const pct = Math.round(score * 100)
  // Semicircle arc: radius=36, circumference of semicircle = pi * r = ~113
  const radius = 36
  const circumference = Math.PI * radius
  const offset = circumference - (score * circumference)
  const color = score >= 0.8 ? '#4ade80' : score >= 0.5 ? '#facc15' : '#f87171'

  return (
    <div className="shrink-0 flex flex-col items-center" style={{ width: 80 }}>
      <svg width="80" height="48" viewBox="0 0 80 48">
        {/* Track */}
        <path
          d="M 4 44 A 36 36 0 0 1 76 44"
          className="safety-gauge-track"
        />
        {/* Fill */}
        <path
          d="M 4 44 A 36 36 0 0 1 76 44"
          className="safety-gauge-fill"
          stroke={color}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
        />
      </svg>
      <span className="text-lg font-bold -mt-2" style={{ color }}>{pct}%</span>
    </div>
  )
}
